# Generated by Django 5.0.1 on 2025-11-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("answer1", models.CharField(max_length=255)),
                ("answer2", models.CharField(max_length=255)),
                ("answer3", models.CharField(max_length=255)),
                (
                    "correct_answer",
                    models.CharField(
                        help_text="Must match one of the three answers.", max_length=255
                    ),
                ),
            ],
        ),
    ]
